### PR TITLE
Added first solution for Ex012 Integer to Roman

### PR DESCRIPTION
**Pull request by Blaster707**

### CODE REVIEW

**Review by iSynaptic — APPROVED** [review]
Nice. Question: is there a recursive solution?

**Comment by Blaster707** [comment]
I believe that I could make a recursive function to solve this; however, running through it in my head, I still think the solution would be O(log N) so I'm not sure if there would be a significant benefit.  The only major adjustment I can think of would be replacing the while loop and making it recursive.  I can write it up if you would like to see it- I may be missing a way that recursion would improve it.

**Comment by iSynaptic** [comment]
I don't think performance would necessarily be better or worse - just that the solution could be more concise. At a minimum, it would be good practice figuring out recursive approaches to problems.

**Comment by Blaster707** [comment]
Sounds good, I'll hit it tonight.

Are there any typical benefits to using recursion over while loops?  It's clear in certain scenarios how it would be beneficial, but some it feels like it doesn't make a difference in terms of execution time.  Do while loops use more memory or do they usually have longer runtimes?

**Review by iSynaptic — APPROVED** [review]
LGTM!

**Comment by iSynaptic** [comment]
I wouldn't say there are "typical" benefits from using recursion over non-recursive means, at least from a CPU/Memory trade-off. Often times the code can be more compact and less error prone - but even that isn't a guarantee. Sometimes CPU/Memory utilization is more efficient - sometimes it's worse. Sometimes non-recursive approaches use CPU cache more efficiently and that can have a huge impact on performance, improving it significantly.

Knowing if/when a recursive approach makes sense comes with experience (and even then with experimentation) - but the more important thing in this case is to make sure you are comfortable designing recursive solutions. They tend to be more difficult for new programmers to conceive of - so practice, practice, practice!

**Pull request merged**
