### PR TITLE
Ex028 findfirstoccurrence

### PR DESCRIPTION
**Pull request by Blaster707**

### CODE REVIEW

**Comment by Blaster707** [comment]
Fascinatingly, on leetcode, the second commit was the "best" solution; the final commit, with just the single line of code, is apparently slower and uses more memory.  Perhaps you can shed some light on this?  Or is it just calculating those results strangely.

**Comment by iSynaptic** [comment]
Not sure - does seem odd.  Could you post screenshots of both results here?

That said, the simpler solution is still the better one IMO - glad you figured that out. Better to have easier to understand code than code that happens to be somewhat faster and hard to comprehend. You only choose the faster/harder to comprehend code when performance and efficiency concerns are top priority or preventing your solution from being viable.

In order:

1. Get It Working (as in, compiles and runs)
2. Get It Right (as in, right output/result)
3. Get It Fast (but only if you *really* need to improve based on testing)

Update: Guess this is roughly based on this: https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast

**Review by iSynaptic — APPROVED** [review]
Nice. Simple solution and I'm glad you didn't leave test assertions commented out.

**Comment by Blaster707** [comment]
I knew from the start there was a simple solution, I just kept trying to do it but I was using the wrong one - indexOfFirst instead of just indexOf.  I knew indexOfFirst would not work since it wanted a char and was not working with a string, but I couldn’t find indexOf.  

So I built it using pointers and then went back afterwards trying a whole lot of stuff (went down a Regex hole for a while) until I went back to the index path and triggered indexOf.

**Comment by iSynaptic** [comment]
Nice thing about struggling with different APIs is you tend to remember them for future use - so not a bad thing.

Regex would probably work here, however building expressions from user input can be dangerous without rigorous input validation. Otherwise I could write input that could execute very slowly and consume lots of resources.  It's called a ReDOS, or Regular Expression Denial of Service attack: https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS

Still, since this is just leetcode and you don't expect the leetcode solution testing system to compromise itself, might be a solution worth looking into.

**Comment by iSynaptic** [comment]
I think moving on to another leetcode problem makes more sense than trying to figure out a regular expression solution. Good idea, but I don't think the payoff will be worth is, especially since you already have a very simple solution.

**Pull request merged**
