### PR TITLE
Added initial solution to Ex036

### PR DESCRIPTION
**Pull request by Blaster707**
This is the initial solution to Ex036.  I decided to create 2 separate functions to check columns and squares, but I think there is a more efficient solution - I will continue to work on it.  In the meantime, let me know what you think of my solution thusfar.

### CODE REVIEW

**Review by iSynaptic — COMMENTED** [review]
So this is where intuition, experience and feeling comes into play - I "feel" like there is a much simpler solution. Not necessarily a more efficient one (although there may be), but one that requires much fewer loops. You really have two "functions" or operations - character selection (what chars should we "look" at) - and duplicate detection (are any of the chars we are "looking" at duplicates). You might be able to factor those two separate concerns into separate functions and then combine/compose them together to get your total solution. Just a thought...

**Comment by iSynaptic** [comment]
One other bit of feedback: can you do this with fewer `var`s? Remember that `when` is an expression (eg. `val foo = when(...) { ... }`)

**Comment by Blaster707** [comment]
I couldn't remember how to write that- thank you!!  Yes, I thought there was a simpler solution but couldn't come up with it.  I'll work on simplifying it down when I'm home.

**Comment by iSynaptic** [comment]
We'll go through this one as part of a future session talking about code organization and refactoring.

**Review by iSynaptic — APPROVED** [review]
Way better implementation! Much easier to follow and understand. The only improvement I could think of would be fewer memory allocations by using `Iterable` instead of `List`, but at this point it's probably not worth spending more time on. The key improvement - readability and understandability - has been made. Nice work!

**Comment by Blaster707** [comment]
I'm not sure if this is exactly what you're looking for in terms of Iterables; I'm less familiar with using them so I may not be using them as effectively as possible.

**Comment by iSynaptic** [comment]
> I'm not sure if this is exactly what you're looking for in terms of Iterables; I'm less familiar with using them so I may not be using them as effectively as possible.

That is the correct first step - you've changed **contract** of the functions to use `Iterable<T>` - the output contract of the two `build` functions and the input contract for the `checkValidity` function.  Going back to our discussions about types representing sets of possible values, `Iterable<T>` is going to be a much larger set of possible values than `List<T>`.  That's because every value in the set of `List<T>` is also a member of the set of values in `Iterable<T>`. But the reverse is not true - not every `Iterable<T>` is also a `List<T>`.  So, by changing the **contract** of the functions, you are saying that they now support a larger set of possible values as inputs and outputs.

However, the **implementation** of the `build` functions has not changed. Internally you are still using the same value - a mutable list that you allocate and then add values to.  In order to actually reduce allocations, you need to return a _different_ value from the set of all possible `Iterable<T>` values - one that doesn't allocate potentially large internal arrays.  Remember, `Iterable<T>` is lazy, `List<T>` is eager. In other words, `Iterable<T>` only calculates one value at a time, whereas `List<T>` has every value calculated by the time it returns from your `build` functions - and since every value has been calculated, it needs to be stored somewhere in memory.

One other thing to keep in mind: `asIterable` just changes the contract the compiler is looking at. One way to think about `asIterable` is this:

```
fun <T> asIterable(input: List<T>): Iterable<T> {
    return input
}
```

As you can see, `asIterable` basically doesn't do anything - it just returns what gets passed in. The only impact is that it tells the compiler that it will be dealing only with the `Iterable<T>` contract from now on, and not the entire `List<T>` contract.  That said, it is just fine to take an existing `CharArray` and call `asIterable` on it, since you must create (aka. allocate) those `CharArray`s to pass them into your `isValidSudoku` function.  The goal isn't to eliminate ALL allocations, only the unnecessary ones. Creating the `CharArray`s is necessary; creating the temporary mutable `List<T>`s is not.

I'll give you a hint on how to pick/build a different value from the set of all possible `Iterable<T>` values - one that is lazily evaluated:

```
val result: Iterable<Char> = Iterable {
    iterator {
        yield(theNextCharToReturn)
        // note: you can use loops to yield multiple times inside this iterator block
    }
}
```

Some more reading material:

- https://kotlinlang.org/docs/iterators.html
- https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/iterator.html
- https://typealias.com/guides/kotlin-sequences-illustrated-guide/

**NOTE**: The last link talks about `Sequence<T>`, which is very similar to `Iterable<T>`. The key difference is sequences are expected to be lazy - iterable have no such expectations; in fact, assume for the most part that are not lazy, even though they CAN be lazy.  Still - the article does a good job at illustrating the difference between eager and lazy evaluation.

**Comment by iSynaptic** [comment]
Follow up: The reality is, many Java/Kotlin shops would look at your code and think it's just fine. Most think nothing of allocating temporary lists in memory.  That said, I'm trying to teach you to think about these things because it will impact the performance and flexibility of your solutions if you "just use lists".  I've seen switching to lazy collection evaluation improve the performance of HTTP APIs by multiple *orders of magnitude* when applied consistently.

All that to say, I'm glad you are trying to figure iterables out - it is a sign of an "engineer" and not just a "coder" - but I highly doubt you will be quizzed on the difference between eager and lazy collection evaluation in an interview situation. In fact, I would stick with lists in an interview, unless the interviewer said "could you eliminate the unnecessary temporary lists". Jumping to lazy iterables right away might confuse an interviewer who themselves is not familiar with them (a common occurrence, sadly).

**Comment by Blaster707** [comment]
Ah, that's good to know.  I certainly see the memory allocation benefits- am I understanding correctly that I would have to rewrite the build functions for subBoxes and columns be iterator functions, feeding one value at a time into the validator function, having the validator check each value one at a time as it's fed in, and then having the validator be the only function building a list or map (since it needs to be able to compare to prior values)?  I've only just briefly looked at those articles so I'm still getting a grasp on it.

**Comment by iSynaptic** [comment]
Yes, that is correct.

**Comment by iSynaptic** [comment]
Did you merge the wrong PR? I was under the impression you wanted to get iterables working? That's okay if you don't - but just wanted to call out that I commented on PR #16 as the one you could probably merge...

**Comment by Blaster707** [comment]
My mistake - you are correct, I did close the wrong one.  Is there a way to unmerge and reopen the pull request?  Or should I just open a new one?

**Comment by Blaster707** [comment]
Looks like I'll just have to open a new pull request for the further changes, which is fine.  I'll take care of that tonight.

**Comment by iSynaptic** [comment]
> My mistake - you are correct, I did close the wrong one. Is there a way to unmerge and reopen the pull request? Or should I just open a new one?

You "can't" unmerge because it's now part of the master branches history. Technically you could, but it's very bad form since it would break other clones of the repo in many scenarios.  The better approach would be to create a new PR that reverts the changes - but I wouldn't do that here. Just move forward and create a new PR with new iterable changes...

**Pull request merged**
